# Generated by Django 4.2 on 2023-07-06 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prasad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackinfo',
            name='feedback',
            field=models.TextField(max_length=400),
        ),
    ]
