# Generated by Django 4.2 on 2023-07-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prasad', '0002_alter_feedbackinfo_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackinfo',
            name='feedback',
            field=models.TextField(),
        ),
    ]
