# Generated by Django 4.2 on 2023-07-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prasad', '0003_alter_feedbackinfo_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=260)),
                ('address', models.CharField(max_length=260)),
                ('email', models.EmailField(max_length=260)),
                ('mobile', models.IntegerField()),
                ('subject', models.CharField(max_length=260)),
                ('message', models.TextField()),
            ],
        ),
    ]
