# Generated by Django 4.2 on 2023-07-22 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prasad', '0004_contactinfo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contactinfo',
            table='contactinfos',
        ),
    ]
