# Generated by Django 4.2 on 2023-07-22 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prasad', '0005_alter_contactinfo_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contactinfo',
            table='contactinfo',
        ),
    ]
