# Generated by Django 4.2 on 2023-07-23 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prasad', '0007_remove_contactinfo_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='message',
            field=models.TextField(max_length=400),
        ),
    ]
