# Generated by Django 4.2 on 2023-07-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prasad', '0008_alter_contactinfo_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_name', models.CharField(max_length=250)),
                ('event_name', models.CharField(max_length=250)),
                ('full_name', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250)),
                ('mobile_no', models.IntegerField()),
                ('other_details', models.TextField()),
                ('event_day_choice', models.CharField(choices=[('one-day', 'One-day'), ('two-days', 'Two-days'), ('three-days', 'Three-days'), ('more', 'More')], default='one-day', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceInfo',
            fields=[
                ('sn', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=264)),
                ('img', models.ImageField(blank=True, null=True, upload_to='images')),
                ('content', models.TextField()),
                ('slug', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='FeedbackInfo',
        ),
    ]
