# Generated by Django 4.2 on 2023-07-29 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prasad', '0009_bookinginfo_serviceinfo_delete_feedbackinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinginfo',
            name='tent_size',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
