# Generated by Django 4.2 on 2023-07-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prasad', '0010_bookinginfo_tent_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinginfo',
            name='email',
            field=models.EmailField(max_length=250, null=True),
        ),
    ]
