# Generated by Django 4.2 on 2023-07-29 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prasad', '0011_alter_bookinginfo_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryHandler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
        ),
    ]
