# Generated by Django 4.2 on 2023-07-31 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prasad', '0012_galleryhandler'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='subject',
        ),
    ]
