# Generated by Django 4.2 on 2023-08-03 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prasad', '0013_remove_contactinfo_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='email',
        ),
    ]
