# Generated by Django 4.2 on 2023-08-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prasad', '0014_remove_contactinfo_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceinfo',
            name='sn',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
